create table Student (id int PRIMARY KEY , name varchar(50));
alter table Student modify id int GENERATED by default on null as IDENTITY;
select * from Passport;
create table Passport (id varchar(10) primary key, s_id int references Student(id), place varchar(50));

insert into Student values(1,'SUBHENDU');
insert into Passport values ('Z111222',1,'KOL');
--drop table Student;
student_seq;


CREATE SEQUENCE student_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
--  ALTER TABLE table_name ENABLE ALL TRIGGERS;
  
  CREATE OR REPLACE TRIGGER student_trigger
BEFORE INSERT
ON Student
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.id is null) then
  SELECT student_seq.nextval
  INTO :new.id
  FROM dual;
  end if;
END;

