create table Student (id int PRIMARY KEY , name varchar(50), passport_id varchar(10) references Passport(id));
alter table Student modify id int GENERATED by default on null as IDENTITY;
select * from Student;
create table Passport (id varchar(10) primary key, place varchar(50));
alter table Passport drop column s_id;

insert into Student values(2,'Vignesh','Z111223');
insert into Passport values ('Z111222','KOL');
insert into Passport values ('Z111223','DELHI');
update Passport set s_id = null where id = 'Z111222';

--drop table Passport;

student_seq;

select * from Passport;
delete from Passport;


CREATE SEQUENCE student_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
--  ALTER TABLE table_name ENABLE ALL TRIGGERS;
  
  CREATE OR REPLACE TRIGGER student_trigger
BEFORE INSERT
ON Student
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.id is null) then
  SELECT student_seq.nextval
  INTO :new.id
  FROM dual;
  end if;
END;

